Question 1.A

In [23]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

r = 0.08              
q = 0.0     
T = 0.5
n = 1.0      
S = 100.0      
K = 105.0   
u = 1.3
d = .8
h = T/n

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d))   
f = S * D + B

print(f"{f:0.4f}", f"{D:0.4f}", f"{B:0.4f}")





11.5684 0.5000 -38.4316


Question 1.B

In [24]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

r = 0.08              
q = 0.0     
T = 0.5
n = 1.0      
S = 100.0      
K = 105.0   
u = 1.3
d = .8
h = T/n

fu = putPayoff(u * S, K)
fd = putPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d))   
f = S * D + B

print(f"{f:0.4f}", f"{D:0.4f}", f"{B:0.4f}")

12.4513 -0.5000 62.4513


Question 2.A

In [27]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

r = 0.08              
q = 0.0     
T = 0.5
n = 1.0      
S = 100.0      
K = 95.0   
u = 1.3
d = .8
h = T/n

fu = putPayoff(u * S, K)
fd = putPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d))   
f = S * D + B

print(f"{f:0.4f}", f"{D:0.4f}", f"{B:0.4f}")

7.4708 -0.3000 37.4708


Question 2.B

Sell option for 16.196 and buy .7 shares by borrowing 53.804. This yields a profit of $.804

Question 2.C

Buy the option and sell .7 shares then lend 53.804. This yields a profit of $.696

Question 3

In [3]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 100.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 2
h = T / n
u = 1.3
d = .8
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i,n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
                    
            
    return Ct[0,0]

B:130 = print("Beta at 130:", np.exp(-r*h)*((u*9 - d*74)/(u-d))) 
B:80 = print("Beta at 80:", np.exp(-r*h)*((u*0 - d*9)/(u-d)))
B:100 = print("Beta at 100:", np.exp(-r*h)*((u*4.1646 - d*38.7250)/(u-d)))

Beta at 130: -91.2749967194707
Beta at 80: -13.835367923793454
Beta at 100: -49.12712403431416


In [4]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[100. 130. 169.]
 [  0.  80. 104.]
 [  0.   0.  64.]]


[[19.994 38.725 74.   ]
 [ 0.     4.165  9.   ]
 [ 0.     0.     0.   ]]


[[0.691 1.    0.   ]
 [0.    0.225 0.   ]
 [0.    0.    0.   ]]




19.993693459343987

Question 4: As the stock price increases, the intial delta increases as well.

In [5]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 80.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = 1.3
d = .8
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i,n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")

                    
            
    return Ct[0,0]
B:135.2 = print("Beta at 135.2:", np.exp(-r*h)*((u*13.16 - d*80.76)/(u-d))) 
B:83.2 = print("Beta at 83.2:", np.exp(-r*h)*((u*0 - d*13.16)/(u-d)))
B:51.2 = print("Beta at 51.2:", np.exp(-r*h)*((u*0 - d*0)/(u-d)))
B:104 = print("Beta at 104:", np.exp(-r*h)*((u*5.8181 - d*42.6999)/(u-d))) 
B:64 = print("Beta at 64:", np.exp(-r*h)*((u*0 - d*5.8181)/(u-d)))
B:80 = print("Beta at 80:", np.exp(-r*h)*((u*2.5722 - d*21.9705)/(u-d)))

Beta at 135.2: -92.50014618854877
Beta at 83.2: -20.501927138379823
Beta at 51.2: 0.0
Beta at 104: -51.793051854476985
Beta at 64: -9.064001693298453
Beta at 80: -27.71604275019723


In [6]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[ 80.   104.   135.2  175.76]
 [  0.    64.    83.2  108.16]
 [  0.     0.    51.2   66.56]
 [  0.     0.     0.    40.96]]


[[11.081 21.971 42.7   80.76 ]
 [ 0.     2.572  5.818 13.16 ]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]]


[[0.485 0.709 1.    0.   ]
 [0.    0.182 0.316 0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]]




11.080555851351969

In [7]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 90.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = 1.3
d = .8
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i,n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
 
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")

                    
            
    return Ct[0,0]

B:152.1 = print("Beta at 152.1:", np.exp(-r*h)*((u*26.68 - d*102.73)/(u-d))) 
B:93.6 = print("Beta at 93.6:", np.exp(-r*h)*((u*0 - d*26.68)/(u-d)))
B:57.6 = print("Beta at 57.6:", np.exp(-r*h)*((u*0 - d*0)/(u-d)))
B:117 = print("Beta at 117:", np.exp(-r*h)*((u*11.7953 - d*52.5999)/(u-d))) 
B:72 = print("Beta at 72:", np.exp(-r*h)*((u*0 - d*11.7953)/(u-d)))
B:90 = print("Beta at 90:", np.exp(-r*h)*((u*5.2147 - d*32.6194)/(u-d)))

Beta at 152.1: -92.5001461885488
Beta at 93.6: -41.56469726838706
Beta at 57.6: 0.0
Beta at 117: -52.084456525543395
Beta at 72: -18.375864830952242
Beta at 90: -37.61622629132517


In [8]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[ 90.   117.   152.1  197.73]
 [  0.    72.    93.6  121.68]
 [  0.     0.    57.6   74.88]
 [  0.     0.     0.    46.08]]


[[ 17.193  32.619  59.6   102.73 ]
 [  0.      5.215  11.795  26.68 ]
 [  0.      0.      0.      0.   ]
 [  0.      0.      0.      0.   ]]


[[0.609 0.817 1.    0.   ]
 [0.    0.328 0.57  0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]]




17.193212548696497

In [9]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 110.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = 1.3
d = .8
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i,n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
 
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")

                    
            
    return Ct[0,0]

B:185.9 = print("Beta at 185.9:", np.exp(-r*h)*((u*53.72 - d*146.67)/(u-d))) 
B:114.4 = print("Beta at 114.4:", np.exp(-r*h)*((u*0 - d*53.72)/(u-d)))
B:70.4 = print("Beta at 70.4:", np.exp(-r*h)*((u*0 - d*0)/(u-d)))
B:143 = print("Beta at 143:", np.exp(-r*h)*((u*23.7498 - d*93.3998)/(u-d))) 
B:88 = print("Beta at 88:", np.exp(-r*h)*((u*0 - d*23.7498)/(u-d)))
B:110 = print("Beta at 110:", np.exp(-r*h)*((u*10.4998 - d*53.9173)/(u-d)))

Beta at 185.9: -92.50014618854877
Beta at 114.4: -83.69023752840151
Beta at 70.4: 0.0
Beta at 143: -85.38269809792716
Beta at 88: -36.99974689597972
Beta at 110: -57.416496005006124


In [10]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[110.   143.   185.9  241.67]
 [  0.    88.   114.4  148.72]
 [  0.     0.    70.4   91.52]
 [  0.     0.     0.    56.32]]


[[ 29.419  53.917  93.4   146.67 ]
 [  0.     10.5    23.75   53.72 ]
 [  0.      0.      0.      0.   ]
 [  0.      0.      0.      0.   ]]


[[0.789 0.974 1.    0.   ]
 [0.    0.54  0.939 0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]]




29.418525943385543

In [11]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 120.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = 1.3
d = .8
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i,n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
 
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")

                    
            
    return Ct[0,0]

B:202.8 = print("Beta at 202.8:", np.exp(-r*h)*((u*67.24 - d*168.64)/(u-d))) 
B:124.8 = print("Beta at 124.8:", np.exp(-r*h)*((u*4.84 - d*67.24)/(u-d)))
B:76.8 = print("Beta at 76.8:", np.exp(-r*h)*((u*0 - d*4.84)/(u-d)))
B:156 = print("Beta at 156:", np.exp(-r*h)*((u*32.2999 - d*110.2999)/(u-d))) 
B:96 = print("Beta at 96:", np.exp(-r*h)*((u*2.1398 - d*32.2999)/(u-d)))
B:120 = print("Beta at 120:", np.exp(-r*h)*((u*15.4173 - d*65.9399)/(u-d)))

Beta at 202.8: -92.5001461885488
Beta at 124.8: -92.50014618854877
Beta at 76.8: -7.540222442990754
Beta at 156: -90.06602918374084
Beta at 96: -44.90284254403941
Beta at 120: -63.69741172092848


In [12]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[120.   156.   202.8  263.64]
 [  0.    96.   124.8  162.24]
 [  0.     0.    76.8   99.84]
 [  0.     0.     0.    61.44]]


[[ 37.345  65.934 110.3   168.64 ]
 [  0.     15.417  32.3    67.24 ]
 [  0.      0.      2.14    4.84 ]
 [  0.      0.      0.      0.   ]]


[[0.842 1.    1.    0.   ]
 [0.    0.628 1.    0.   ]
 [0.    0.    0.126 0.   ]
 [0.    0.    0.    0.   ]]




37.34516043327331

In [13]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 130.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = 1.3
d = .8
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i,n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
 
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")

                    
            
    return Ct[0,0]

B:219.7 = print("Beta at 219.7:", np.exp(-r*h)*((u*80.76 - d*190.61)/(u-d))) 
B:135.2 = print("Beta at 135.2:", np.exp(-r*h)*((u*13.16 - d*80.76)/(u-d)))
B:83.2 = print("Beta at 83.2:", np.exp(-r*h)*((u*0 - d*13.16)/(u-d)))
B:169 = print("Beta at 169:", np.exp(-r*h)*((u*42.6999 - d*127.1999)/(u-d))) 
B:104 = print("Beta at 104:", np.exp(-r*h)*((u*5.8181 - d*42.6999)/(u-d)))
B:130 = print("Beta at 130:", np.exp(-r*h)*((u*21.9705 - d*78.9339)/(u-d)))

Beta at 219.7: -92.5001461885488
Beta at 135.2: -92.50014618854877
Beta at 83.2: -20.501927138379823
Beta at 169: -90.06602918374087
Beta at 104: -51.793051854476985
Beta at 130: -67.35075854736144


In [14]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[130.   169.   219.7  285.61]
 [  0.   104.   135.2  175.76]
 [  0.     0.    83.2  108.16]
 [  0.     0.     0.    66.56]]


[[ 46.576  78.934 127.2   190.61 ]
 [  0.     21.971  42.7    80.76 ]
 [  0.      0.      5.818  13.16 ]
 [  0.      0.      0.      0.   ]]


[[0.876 1.    1.    0.   ]
 [0.    0.709 1.    0.   ]
 [0.    0.    0.316 0.   ]
 [0.    0.    0.    0.   ]]




46.57605994755165

Question 5a.
There isn't any early exercise

In [36]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 100.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def binomialPricer(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pstar = (np.exp((r - q) * h) - d) / (u - d)
    
    price = 0.0
    
    for i in range(nodes):
        prob = binom.pmf(i, n, pstar)
        spotT = S * (u ** i) * (d ** (n - i))
        po = payoff(spotT, K) 
        price += po * prob
        if verbose:
            print(f"({spotT:0.4f}, {po:0.4f}, {prob:0.4f})")
        
    price *= np.exp(-r * T)
    
    return price
    

In [37]:
binomialPricer(S,K,r,v,q,T,n,callPayoff,verbose = True)

(64.4284, 0.0000, 0.1603)
(91.1007, 0.0000, 0.4044)
(128.8147, 33.8147, 0.3400)
(182.1418, 87.1418, 0.0953)


18.282552207370557

Question 5b.
Both the American and European call options have the same price

In [38]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 100.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def binomialPricer(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pstar = (np.exp((r - q) * h) - d) / (u - d)
    
    price = 0.0
    
    for i in range(nodes):
        prob = binom.pmf(i, n, pstar)
        spotT = S * (u ** i) * (d ** (n - i))
        po = payoff(spotT, K) 
        price += po * prob
        if verbose:
            print(f"({spotT:0.4f}, {po:0.4f}, {prob:0.4f})")
        
    price *= np.exp(-r * T)
    
    return price

In [39]:
binomialPricer(S,K,r,v,q,T,n,callPayoff,verbose = True)

(64.4284, 0.0000, 0.1603)
(91.1007, 0.0000, 0.4044)
(128.8147, 33.8147, 0.3400)
(182.1418, 87.1418, 0.0953)


18.282552207370557

Question 5c.
Put-call parity does hold: 12.3039

In [40]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 100.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def binomialPricer(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pstar = (np.exp((r - q) * h) - d) / (u - d)
    
    price = 0.0
    
    for i in range(nodes):
        prob = binom.pmf(i, n, pstar)
        spotT = S * (u ** i) * (d ** (n - i))
        po = payoff(spotT, K) 
        price += po * prob
        if verbose:
            print(f"({spotT:0.4f}, {po:0.4f}, {prob:0.4f})")
        
    price *= np.exp(-r * T)
    
    return price

In [41]:
binomialPricer(S,K,r,v,q,T,n,putPayoff,verbose = True)

(64.4284, 30.5716, 0.1603)
(91.1007, 3.8993, 0.4044)
(128.8147, 0.0000, 0.3400)
(182.1418, 0.0000, 0.0953)


5.9786051141009695

Question 5d. 

In [42]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 100.0
K = 95.0
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def amerBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            Ct[j] = np.maximum(Ct[j], K-St[j])
            print(Ct)
            
    return Ct[0]

In [43]:
amerBinomPricerRecursive(S,K,r,v,q,T,n,putPayoff,verbose = True)

[ 0.          0.          3.89933488 30.57157332]
[ 0.          0.          3.89933488 30.57157332]
[ 0.          2.06235672  3.89933488 30.57157332]
[ 0.          2.06235672 20.40351726 30.57157332]
[ 1.09077967  2.06235672 20.40351726 30.57157332]
[ 1.09077967 11.7087201  20.40351726 30.57157332]
[ 6.67790123 11.7087201  20.40351726 30.57157332]


6.677901227132065

The reason the prices differ is because of the option to exercise early.

Question 6a.

In [58]:
import numpy as np
from scipy.stats import binom

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 40.0
K = 40.0
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d) 
nodes = n + 1

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))                        
B = np.exp(-r * h) * ((u * fd - d * fu)/ (u - d)) 


def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    St = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        
    
    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
        

    if verbose:
        print(St)
        print("\n")
                    
print(u)
print(d)
            

1.1454617381452392
0.8966038495199921


In [59]:
euroBinomPricerRecursiveMatrix(S,K,r,v,q,T,n,callPayoff,verbose = True)

[[40.         45.81846953 52.48330374 60.11761633]
 [ 0.         35.86415398 41.08101616 47.05673217]
 [ 0.          0.         32.15593852 36.83339723]
 [ 0.          0.          0.         28.83113826]]




Question 6b. American Put

In [57]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 40.0
K = 40.0
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def amerBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            Ct[j] = np.maximum(Ct[j], K-St[j])
            print(Ct)
            
    return Ct[0]

In [60]:
amerBinomPricerRecursive(S,K,r,v,q,T,n,putPayoff,verbose = True)

[ 0.          0.          3.16660277 11.16886174]
[ 0.          0.          3.16660277 11.16886174]
[ 0.          1.65788424  3.16660277 11.16886174]
[ 0.          1.65788424  7.84406148 11.16886174]
[ 0.86799019  1.65788424  7.84406148 11.16886174]
[ 0.86799019  4.8747172   7.84406148 11.16886174]
[ 2.95422756  4.8747172   7.84406148 11.16886174]


2.9542275627722927

European Put

In [61]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 40.0
K = 40.0
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            print(Ct)
            
    return Ct[0]

In [62]:
euroBinomPricerRecursive(S,K,r,v,q,T,n, putPayoff, verbose = True)

[ 0.          0.          3.16660277 11.16886174]
[ 0.          0.          3.16660277 11.16886174]
[ 0.          1.65788424  3.16660277 11.16886174]
[ 0.          1.65788424  7.31426795 11.16886174]
[ 0.86799019  1.65788424  7.31426795 11.16886174]
[ 0.86799019  4.59734223  7.31426795 11.16886174]
[ 2.80900708  4.59734223  7.31426795 11.16886174]


2.8090070796101805

American Call

In [63]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 40.0
K = 40.0
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def binomialPricer(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pstar = (np.exp((r - q) * h) - d) / (u - d)
    
    price = 0.0
    
    for i in range(nodes):
        prob = binom.pmf(i, n, pstar)
        spotT = S * (u ** i) * (d ** (n - i))
        po = payoff(spotT, K) 
        price += po * prob
        if verbose:
            print(f"({spotT:0.4f}, {po:0.4f}, {prob:0.4f})")
        
    price *= np.exp(-r * T)
    
    return price
    

In [64]:
binomialPricer(S,K,r,v,q,T,n,callPayoff, verbose = True)

(28.8311, 0.0000, 0.1494)
(36.8334, 0.0000, 0.3964)
(47.0567, 7.0567, 0.3507)
(60.1176, 20.1176, 0.1034)


4.377429513517247

European Call

In [65]:
import numpy as np

def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

S = 40.0
K = 40.0
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
h = T / n
u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
pstar = (np.exp((r - q) * h) - d) / (u - d)
nodes = n + 1

def binomialPricer(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pstar = (np.exp((r - q) * h) - d) / (u - d)
    
    price = 0.0
    
    for i in range(nodes):
        prob = binom.pmf(i, n, pstar)
        spotT = S * (u ** i) * (d ** (n - i))
        po = payoff(spotT, K) 
        price += po * prob
        if verbose:
            print(f"({spotT:0.4f}, {po:0.4f}, {prob:0.4f})")
        
    price *= np.exp(-r * T)
    
    return price

In [66]:
binomialPricer(S,K,r,v,q,T,n,callPayoff,verbose = True)

(28.8311, 0.0000, 0.1494)
(36.8334, 0.0000, 0.3964)
(47.0567, 7.0567, 0.3507)
(60.1176, 20.1176, 0.1034)


4.377429513517247